<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.love233niang</groupId>
        <artifactId>love233niang-seckill</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>love233niang-seckill-user</artifactId>
    <packaging>jar</packaging>

    <name>${artifactId}</name>
    <description>用户模块，放置用户登录、注册、发送验证码等接口</description>



    <dependencies>
        <dependency>
            <groupId>com.love233niang</groupId>
            <artifactId>love233niang-seckill-common</artifactId>
        </dependency>


    </dependencies>
</project>
